import { faCheck, faFemale, faMale, faMosque, faOm, faXmark } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import useDateAndTime from "../hooks/useDateAndTime";

const StudentsDetailsComponents = ({ stuData }) => {

    const { convertDateAndTime } = useDateAndTime();

    return (
        <div className="my-2 bg-sky-100 p-2 rounded-lg shadow-md">
            <h1 className="capitalize font-bold text-gray-600">{<FontAwesomeIcon icon={(stuData.gender === "" || stuData.gender === null || stuData.gender === undefined) ? faXmark : faCheck} color={(stuData.gender === "" || stuData.gender === null || stuData.gender === undefined) ? "red" : "green"} />} Gender: {(stuData.gender === "" || stuData.gender === null || stuData.gender === undefined) ? <span className="text-gray-300">Not Set</span> : <span className={`${stuData.gender === "male" ? "text-blue-800" : "text-pink-600"}`}>{stuData.gender} <FontAwesomeIcon icon={stuData.gender === "male" ? faMale : faFemale} /></span>}</h1>
            <h1 className="capitalize font-bold text-gray-600">{<FontAwesomeIcon icon={(stuData.father_name === "" || stuData.father_name === null || stuData.father_name === undefined) ? faXmark : faCheck} color={(stuData.father_name === "" || stuData.father_name === null || stuData.father_name === undefined) ? "red" : "green"} />} Father: {(stuData.father_name === "" || stuData.father_name === null || stuData.father_name === undefined) ? <span className="text-gray-300">Not Set</span> : <span className="text-sky-800">{stuData.father_name}</span>}</h1>
            <h1 className="capitalize font-bold text-gray-600">{<FontAwesomeIcon icon={(stuData.mother_name === "" || stuData.mother_name === null || stuData.mother_name === undefined) ? faXmark : faCheck} color={(stuData.mother_name === "" || stuData.mother_name === null || stuData.mother_name === undefined) ? "red" : "green"} />} Mohter: {(stuData.mother_name === "" || stuData.mother_name === null || stuData.mother_name === undefined) ? <span className="text-gray-300">Not Set</span> : <span className="text-sky-800">{stuData.mother_name}</span>}</h1>
            <h1 className="capitalize font-bold text-gray-600">{<FontAwesomeIcon icon={(stuData.stu_dateOfBirth === "" || stuData.stu_dateOfBirth === null || stuData.stu_dateOfBirth === undefined) ? faXmark : faCheck} color={(stuData.stu_dateOfBirth === "" || stuData.stu_dateOfBirth === null || stuData.stu_dateOfBirth === undefined) ? "red" : "green"} />} Date of Birth: {(stuData.stu_dateOfBirth === "" || stuData.stu_dateOfBirth === null || stuData.stu_dateOfBirth === undefined) ? <span className="text-gray-300">Not Set</span> : <span className="text-sky-800">{convertDateAndTime(new Date(stuData.stu_dateOfBirth).getTime(), "dateOnly")}</span>}</h1>
            <h1 className="capitalize font-bold text-gray-600">{<FontAwesomeIcon icon={(stuData.stu_birthCerNum === "" || stuData.stu_birthCerNum === null || stuData.stu_birthCerNum === undefined) ? faXmark : faCheck} color={(stuData.stu_birthCerNum === "" || stuData.stu_birthCerNum === null || stuData.stu_birthCerNum === undefined) ? "red" : "green"} />} Birth Cer. No.: {(stuData.stu_birthCerNum === "" || stuData.stu_birthCerNum === null || stuData.stu_birthCerNum === undefined) ? <span className="text-gray-300">Not Set</span> : <span className="text-sky-800">{stuData.stu_birthCerNum}</span>}</h1>
            <h1 className="capitalize font-bold text-gray-600">{<FontAwesomeIcon icon={(stuData.mobile_no === "" || stuData.mobile_no === null || stuData.mobile_no === undefined) ? faXmark : faCheck} color={(stuData.mobile_no === "" || stuData.mobile_no === null || stuData.mobile_no === undefined) ? "red" : "green"} />} Mobile-1: {(stuData.mobile_no === "" || stuData.mobile_no === null || stuData.mobile_no === undefined) ? <span className="text-gray-300">Not Set</span> : <span className="text-sky-800">{stuData.mobile_no}</span>}</h1>
            <h1 className="capitalize font-bold text-gray-600">{<FontAwesomeIcon icon={(stuData.mobile_2 === "" || stuData.mobile_2 === null || stuData.mobile_2 === undefined) ? faXmark : faCheck} color={(stuData.mobile_2 === "" || stuData.mobile_2 === null || stuData.mobile_2 === undefined) ? "red" : "green"} />} Mobile-2: {(stuData.mobile_2 === "" || stuData.mobile_2 === null || stuData.mobile_2 === undefined) ? <span className="text-gray-300">Not Set</span> : <span className="text-sky-800">{stuData.mobile_2}</span>}</h1>
            <h1 className="capitalize font-bold text-gray-600">{<FontAwesomeIcon icon={(stuData.religion === "" || stuData.religion === null || stuData.religion === undefined) ? faXmark : faCheck} color={(stuData.religion === "" || stuData.religion === null || stuData.religion === undefined) ? "red" : "green"} />} Religion: {(stuData.religion === "" || stuData.religion === null || stuData.religion === undefined) ? <span className="text-gray-300">Not Set</span> : <span className={`${stuData.religion === "islam" ? "text-green-800" : "text-orange-600"}`}>{stuData.religion} <FontAwesomeIcon icon={stuData.religion === "islam" ? faMosque : faOm} /></span>}</h1>
        </div>
    );
};

export default StudentsDetailsComponents;